### ISSUE TITLE
Wrong permissions in Videomass AppImage

### ISSUE THREAD

**Issue by probonopd** [jeanslack/Videomass#4] opened 2020-07-31 17:09 UTC
Hello, thanks for making an AppImage. However, it does not run with Firejail. Its top-level directory is root-owned and permissions are set not to be readable by anyone else.

Can you please set 0755 as the permissions for the top-level (AppDir) directory?
Please reply here if something should be unclear.

Thank you very much.

References:
* https://github.com/AppImage/appimage.github.io/pull/2133
* https://github.com/AppImage/AppImageKit/issues/1032

**Comment by jeanslack** [comment] 2020-08-01 08:18
Hello, sorry for this mistake. I hadn't checked the permissions yet. My question is: only the top level directory (AppDir) must be set with 0775 permissions or also the subfolders opt/ and usr/ in a recursive way? 

Thanks for this report.

**Comment by probonopd** [comment] 2020-08-01 09:01
Hi @jeanslack all directories should be 0775. I'd be interested how you ended up with some not being that.

**Comment by jeanslack** [comment] 2020-08-01 11:19
I honestly don't know how it happened, I took the following steps:
- I was read the README on https://github.com/niess/python-appimage
- I downloaded python3.7.7-cp37-cp37m-manylinux1_x86_64.AppImage from [here](https://github.com/niess/python-appimage/releases)
- I ran `python3.7.7-cp37-cp37m-manylinux1_x86_64.AppImage --appimage-extract` (after the `chmod +x`)
- `export PATH="$(pwd)/squashfs-root/usr/bin:$PATH"`
- I installed wxPython, PyPubSub and videomass with pip command
- I edit the `AppRun` and `python3.7.7.appdata.xml` files
- I added `videomass.desktop` and `videomass.png`
- I manually included `usr/x86_64-linux-gnu` with `libjbig.so.0` and `libjpeg.so.62` and little else. 
- Finally I used [linuxdeploy-x86_64.AppImage](linuxdeploy-x86_64.AppImage) to create appimage with `--appdir squashfs-root --output appimage` options

maybe something I don't remember is missing.   
Now I try it all over again because if I extract python3.7.8-cp37-cp37m-manylinux1_x86_64.AppImage the permissions are correct.

**Comment by probonopd** [comment] 2020-08-01 11:22
Thank you very much @jeanslack

**Comment by jeanslack** [comment] 2020-08-01 11:37
Thanks to you @probonopd

**Comment by jeanslack** [comment] 2020-08-03 11:54
hello @probonopd, I have solved the problem of permissions which are now fixed on 0775, but by checking the mounting in /tmp the owner always remains root. Is this correct behavior?

`./Videomass-3.0.0-1_x86_64.AppImage`   

`ls -la /tmp/ `
```
drwxr-xr-x  4 root     root        0 ago  3 09:22 .mount_VideomeFvMws
```

`ls -l /tmp/.mount_VideomeFvMws`   
```
-rwxr-xr-x 1 root root 1310 ago  3 09:21 AppRun
drwxr-xr-x 3 root root    0 ago  3 09:18 opt
drwxr-xr-x 5 root root    0 ago  3 09:18 usr
-rw-r--r-- 1 root root  200 ago  3 09:22 videomass.desktop
lrwxrwxrwx 1 root root   50 ago  3 09:21 videomass.png -> usr/share/icons/hicolor/128x128/apps/videomass.png
```

**Comment by probonopd** [comment] 2020-08-03 11:59
Yes, that looks good - please let me know once it is available for download so that I can re-run the test. Thanks!

**Comment by jeanslack** [comment] 2020-08-03 12:04
Ok thank you very much, is already available on https://sourceforge.net

**Comment by jeanslack** [comment] 2020-08-03 12:08
Also, if this can be useful, I found that by using linuxdeploy-x86_64.AppImage to make the videomass AppImage package causes the permissions to change to 0600 during the extraction with the `./Videomass-3.0.0-1_x86_64.AppImage --appimage-extract` command. So repackaging the permissions remain 0600.

The permissions are correct on the appdir:
`ls -l`
`drwxr-xr-x 4 gianluca gianluca      4096 ago  2 18:02 squashfs-root`
`linuxdeploy-x86_64.AppImage --appdir squashfs-root --output appimage`
`./Videomass-x86_64.AppImage`
`ls -l /tmp/.mount_VideomeFvMws`
`drwxr-xr-x  4 root     root        0 ago  3 13:26 .mount_VideommHuAq1`

The problem is here:   
`./Videomass-x86_64.AppImage --appimage-extract`
`ls -l`
`drwx------ 4 gianluca gianluca      4096 ago  3 13:31 squashfs-root`

All this does not occur using appimagetool always.

**Comment by probonopd** [comment] 2020-08-03 12:10
is this still the case with the latest continuous build of linuxdeploy?

**Comment by jeanslack** [comment] 2020-08-03 12:13
now I try with the latest. I will let you know.

**Comment by jeanslack** [comment] 2020-08-03 12:36
> is this still the case with the latest continuous build of linuxdeploy?

unfortunately yes, it is still the case

**Closed as completed** 2020-08-04 22:01 UTC
