### ISSUE TITLE
Problem opening Videomass on macOS

### ISSUE THREAD

**Issue by Gabe-LS** [jeanslack/Videomass#146] opened 2022-08-25 07:57 UTC
Hello, I downloaded Videomass a minute ago for the first time, and I had to run the following command in the Terminal app to make it launch properly on my Mac. I'm using macOS 12.5.1 on an Intel-based MacBook Pro.

`sudo xattr -r -d com.apple.quarantine /Applications/Videomass.app`

**Comment by jeanslack** [comment] 2023-02-01 09:24
I assume you used the dmg installer. However, I'm closing this issue as I have no way to reproduce your problem and I don't plan to provide this type of support yet due to this other [issue](https://github.com/jeanslack/Videomass/issues/165).

**Closed as completed by jeanslack** 2023-02-01 09:24 UTC
