### ISSUE TITLE
Version 4.0.1 After Installation always giving error on startup

### ISSUE THREAD

**Issue by bitsky6** [jeanslack/Videomass#131] opened 2022-06-05 16:26 UTC
![image](https://user-images.githubusercontent.com/57507315/172060482-167205ad-27f2-44e5-aa00-ad81a53b99b7.png)

**Comment by jeanslack** [comment] 2022-06-08 21:57
Sorry for the delay, I've been very busy lately.
I have never encountered such a problem so far. Seems like a problem in the wxPython library. 

Could you give me some information please?
- What operating system are you using?
- Python version?
- WxPython version?

**Comment by bitsky6** [comment] 2022-06-09 16:27
Hey,

I'm running Windows 11 25131.100
But I have ran on an older Windows 11 on my Laptop and the same is there.

Python 3.10.5
WxPython  dont have and cant install it either.

**Comment by bitsky6** [comment] 2022-06-09 18:47
Managed to install WxPython 4.1.1 and reverted to Python 3.9.13 but having same error

**Comment by bitsky6** [comment] 2022-06-09 18:49
For now I am using the Portable Version as that one is working.

**Comment by jeanslack** [comment] 2022-06-09 21:17
> Managed to install WxPython 4.1.1 and reverted to Python 3.9.13 but having same error

Videomass should start with Python 3.9.13 and wxPython 4.1.1
Instead with python 3.10 there are some incompatibilities with wxPython that I believe are about to be resolved by the developers. Hope they release the new version soon.

> For now I am using the Portable Version as that one is working.

For information, the portable version was built with Python 3.7.9 and wxPython 4.0.7

Anyway I'll try to investigate, the problem is that I can only use Windows 10 for testing and not Windows 11.

**Comment by RusselNash10121** [comment] 2023-02-06 20:59
Is this the same error as in openSUSE Tumbleweed x86_64 via AppImage? (It probably doesn't matter but the system has KDE Plasma 5.27 beta, python 3.10.9, libwx 3.2.1 and libtiff6 (4.5.0).)

Videomass 4.0.2:
Traceback (most recent call last):
  File "/tmp/.mount_VideomGjz5jN/usr/bin/videomass", line 6, in <module>
    from videomass.gui_app import main
  File "/tmp/.mount_VideomGjz5jN/opt/python3.9/lib/python3.9/site-packages/videomass/gui_app.py", line 33, in <module>
    import wx
  File "/tmp/.mount_VideomGjz5jN/opt/python3.9/lib/python3.9/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/tmp/.mount_VideomGjz5jN/opt/python3.9/lib/python3.9/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: libtiff.so.5: cannot open shared object file: No such file or directory

Videomass 4.0.5:
Traceback (most recent call last):
  File "/tmp/.mount_VideomH7pI3s/usr/bin/videomass", line 6, in <module>
    from videomass.gui_app import main
  File "/tmp/.mount_VideomH7pI3s/opt/python3.9/lib/python3.9/site-packages/videomass/gui_app.py", line 31, in <module>
    import wx
  File "/tmp/.mount_VideomH7pI3s/opt/python3.9/lib/python3.9/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/tmp/.mount_VideomH7pI3s/opt/python3.9/lib/python3.9/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: libtiff.so.5: cannot open shared object file: No such file or directory

**Comment by jeanslack** [comment] 2023-02-06 21:42
Hello @RusselNash10121 
It's not the same problem, yours is about AppImage. Can you please open a new issue using the [Bug report](https://github.com/jeanslack/Videomass/issues/new?assignees=&labels=&template=bug_report.md&title=) form?

**Comment by jeanslack** [comment] 2023-02-06 22:32
Hello @bitsky6 

**Here some news:**
Platform: Windows 64bit v10.0.19045
Python: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
wxPython: 4.2.0 msw (phoenix) wxWidgets 3.2.0
  
- I tried running Videomass from source code (latest release v4.0.5).
- I tried to pip install videomass v4.0.5.

On both attempts I had no problems and Videomass started up as expected. On Windows 11 it should also work.
I remind you that wxPython v4.1.1 is not compatible with Python 3.10, and wxPython v4.2.0 works correctly with Python 3.10 but you should pip install attrdict3 first.

However, this doesn't seem to be a directly related problem with Videomass, but it is related to incorrect installation of third party packages.

**Closed as completed by jeanslack** 2023-02-06 22:32 UTC
Labels: invalid
