### ISSUE TITLE
Portable v3.3.8 - Windows Defender detects Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by shayaknyc** [jeanslack/Videomass#16] opened 2021-02-22 19:40 UTC
Hey folks, wanted to give this a shot. Downloaded portable version and tried to open the .7z archive and windows defender immediately blocked it. I opened it anyway, and then ran another scan, got the same issue - windows defender will not allow this to execute and claims it's infected with Trojan:Script/Wacatac.B!ml. Any assurances this is a false positive?

**Comment by jeanslack** [comment] 2021-02-23 08:06
Thanks for the report, can I ask you where did you download the file?
I checked using clamav antivirus on Linux. The scan on compressed archive and on the unzipped folder do not report anything to me:

----------- SCAN SUMMARY -----------
Known viruses: 8559039
Engine version: 0.102.4
Scanned directories: 0
Scanned files: 1
Infected files: 0
Data scanned: 0.00 MB
Data read: 58.82 MB (ratio 0.00:1)
Time: 25.995 sec (0 m 25 s)

----------- SCAN SUMMARY -----------
Known viruses: 8559039
Engine version: 0.102.4
Scanned directories: 64
Scanned files: 438
Infected files: 0
Data scanned: 56.48 MB
Data read: 230.75 MB (ratio 0.24:1)
Time: 67.190 sec (1 m 7 s)

Anyway, I'll try to check on Windows too.

**Comment by jeanslack** [comment] 2021-02-23 10:24
I just checked with windows defender. I confirm Trojan:Script/Wacatac.B!
In the log details appears to be the Videomass.exe executable.

Since the executable is created by pyinstaller, I did a search and it appears to be a false positive (but I reserve the right to confirm it).
Here are some sources: 
[https://github.com/pyinstaller/pyinstaller/issues/5492](https://github.com/pyinstaller/pyinstaller/issues/5492)
[https://github.com/pyinstaller/pyinstaller/issues/4724](https://github.com/pyinstaller/pyinstaller/issues/4724)
[https://github.com/pyinstaller/pyinstaller/issues/4633](https://github.com/pyinstaller/pyinstaller/issues/4633)

**Comment by aubreyz** [comment] 2021-02-24 15:32
Some problem here - I'm going to stop using until resolved. Too much risk to run bypass mechanisms.

The other complication is that the version that is causing the problem is not 3.3.8 at all -- or at least not labelled as such. 

On the releases page under 3.3.8 the portable version actually has a filename 3.3.6 -- it is that version that is captured as a virushttps://github.com/jeanslack/Videomass/releases

3.3.7 is fine

**Comment by jeanslack** [comment] 2021-02-24 20:33
@shayaknyc 
Sorry I'm late, but it was a busy day for me today. 

@aubreyz 
Yes indeed, I forgot to correct the version number on the folder, even though the actual version upgrade is v3.3.8.
I noticed the error yesterday during the antivirus tests. But I didn't know that this involved all these problems.

However now I remove that file and fix the version number on the folder and put it back in the repo.

**Comment by shayaknyc** [comment] 2021-02-24 21:09
@jeanslack 
> Sorry I'm late, but it was a busy day for me today.

No worries at all! Thanks for being so responsive!

**Comment by jeanslack** [comment] 2021-02-25 09:54
Portable videomass renamed to correct version. I re-scanned the unzipped folder with windows defender.

Result:
Trojan:Script/Wacatac.B! is no longer there, but another appeared: Trojan:Win32/Zpevdo.B always on the Videomass.exe executable.

[The official solution](https://github.com/pyinstaller/pyinstaller/issues/4633) to this is, to send an advanced analysis of the File to your Antivirus Vendor, and making a False Positive claim.

**Comment by shayaknyc** [comment] 2021-02-25 16:47
@jeanslack I've submitted the videomass.exe to MS Windows Defender. Let's see....

**Comment by shayaknyc** [comment] 2021-02-25 16:58
Oh man, the online submission I just made was updated to show it's "clean" of Wacatac, but is now coming up as positive for: Trojan:Win32/Glupteba!ml

It's still pending review, however.

**Comment by shayaknyc** [comment] 2021-02-25 17:09
I just checked the videomass.exe on virustotal.com, not looking good:
https://www.virustotal.com/gui/file/57ebc8edb6e5d39e0213841b3c3fb73173fcb366be1591fe90d19cd4dc5afde1/detection

**Comment by shayaknyc** [comment] 2021-02-25 22:41
Just received the following reply from MS Windows Defender:


videomass.exe
Submission ID: 0cfacae8-953c-4816-81d8-399e5229cc83
Status: Completed
Submitted: Feb 25, 2021 11:46:44 AM
User Opinion: Incorrect detection
Analyst comments:

                We have removed the detection.  Please follow the steps below to clear cached detection and obtain the latest malware definitions.

     1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
     2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
#     3. Run "MpCmdRun.exe -SignatureUpdate"

**Comment by jeanslack** [comment] 2021-02-26 08:45
Hello @shayaknyc, 
Today I also submitted videomass.exe to MS Windows Defender. I'm waiting for the report...
Anyway, thanks for your cooperation.

**Comment by jeanslack** [comment] 2021-02-27 08:52
The virus problem appears solved, at least with the Windows defender antivirus. I will close this issue as soon as possible.
[Submission history - Microsoft Security Intelligence.pdf](https://github.com/jeanslack/Videomass/files/6054008/Submission.history.-.Microsoft.Security.Intelligence.pdf)
[Submission details (e4d49d6e-1169-4fe3-95d3-4f6fbc23fab7) - Microsoft Security Intelligence.pdf](https://github.com/jeanslack/Videomass/files/6054005/Submission.details.e4d49d6e-1169-4fe3-95d3-4f6fbc23fab7.-.Microsoft.Security.Intelligence.pdf)

However, a recent scan with VirusTotal may still report this on many other antiviruses: https://www.virustotal.com/gui/file/57ebc8edb6e5d39e0213841b3c3fb73173fcb366be1591fe90d19cd4dc5afde1/detection
So, if this is your case, please report it to your **antivirus vendor**, and making a **False Positive** claim.

**Closed as completed** 2021-02-27 15:44 UTC

**Comment by wh1t3h47** [comment] 2025-04-18 12:09
hi @shayaknyc

Av is picking up pyinstaller because it's used by malware, such as project LaZagne, which is bundled with pyinstaller.

Unfortunately MS Defender is not very intelligent on this, and uses ML to detect statistical similarities, so does a lot of different AVs.

Maybe try using nuitka or cython would solve the issue, nuitka might "just work", but cython would require some refactoring probably
